name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6"
          bundler-cache: true

      - name: Lint (RuboCop)
        run: bundle exec rubocop

      - name: Test (Minitest)
        run: bundle exec ruby -e 'require File.expand_path("test/test_helper.rb"); Dir["test/**/*_test.rb"].sort.each { |f| require File.expand_path(f) }'

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: coverage/lcov.info
          format: lcov
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
