name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6"
          bundler-cache: true

      - name: Lint (RuboCop)
        run: bundle exec rubocop

      - name: Test (Minitest)
        run: bundle exec ruby -e 'Dir["test/**/*_test.rb"].sort.each { |f| require File.expand_path(f) }'
