name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ruby:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6"
          bundler-cache: true

      - name: Lint
        run: |
          bundle exec rubocop

      - name: Test
        run: |
          bundle exec ruby -e 'Dir["test/**/*_test.rb"].sort.each { |f| require File.expand_path(f) }'
