name: RuboCop

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true

      - name: Run RuboCop
        run: bundle exec rubocop
